# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            CBGL
tagline:          Hmmm
description:      Catatan biar gak lupa
url:              https://blog.labseni.com/
baseurl:          # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                

author:
  name:           'Aziz Faozi'
  url:            https://twitter.com/phaoziaziz

paginate:         10
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            3.5.3
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
github:
  repo:             https://github.com/faoziaziz
disqus:
  shortname: faoziaziz

gems: ['kramdown', 'jekyll-gist', 'jekyll-paginate']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']
